#!/usr/bin/env python3
"""Re-export the AgentCore deploy demo bundle: logs/agentcore-deploy-demo{,.tar.gz}.

    ./venv/bin/python scripts/export-deploy-demo.py
    ./venv/bin/python scripts/export-deploy-demo.py --check   # report drift, write nothing

Why a script. The bundle was assembled by hand once and then went stale in the way
that matters most: it carries COPIES of `a2a-agent-registry/common/*` and
`shared/agent_registry.py`, and a copy of a sub-agent's runtime code is exactly the
thing that must not drift. By 2026-08-15 the copied `common/server.py` imported a
module (`common/a2a_session.py`) the bundle did not contain, so a demo agent built
from it would have crashed on import — with the tarball still looking fine.

`logs/` is gitignored, so the bundle itself is not in version control. What IS in
version control is everything needed to rebuild it: this script, the runbook
(`docs/agentcore-deploy-runbook.md`) and the repo code it copies. The only part that
lives solely in the bundle is the demo-specific code (the air-quality agent's own
`main.py` / `deploy_runtime.py` / `register_record.py` / `teardown.py`, the skill
bundle's `publish_skill.py`, the cards and prompts). This script refuses to write a
bundle if those are missing rather than producing a broken one — recover them from
the existing tarball first.

What it refreshes, every run:
  - `common/` from a2a-agent-registry/common (tests and caches excluded)
  - `agent_registry.py` in both bundles from shared/agent_registry.py
  - `demo-config.json` in both bundles, from cdk-outputs.json + agentcore-state.json
  - the runbook and the index README
  - the tarball
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tarfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT_DIR = REPO / "logs" / "agentcore-deploy-demo"
TARBALL = REPO / "logs" / "agentcore-deploy-demo.tar.gz"

AGENT_BUNDLE = OUT_DIR / "demo-agent-air-quality"
SKILL_BUNDLE = OUT_DIR / "demo-skill-indoor-air-report"

# Files that exist ONLY in the bundle. They are the demo itself; this script copies
# repo code around them and never generates them.
DEMO_ONLY = {
    AGENT_BUNDLE: ["main.py", "invoke_local.py", "deploy_runtime.py",
                   "register_record.py", "teardown.py", "requirements.txt",
                   "README.md", "air-quality/card.json",
                   "air-quality/system_prompt.md"],
    SKILL_BUNDLE: ["publish_skill.py", "requirements.txt", "README.md",
                   "skill/SKILL.md"],
}

# Copied straight out of the repo. `common/` is copied wholesale rather than listed,
# so a module added upstream (a2a_session.py was, and its absence would have been an
# ImportError at container start) travels automatically.
COMMON_SRC = REPO / "a2a-agent-registry" / "common"
COMMON_IGNORE = shutil.ignore_patterns("tests", "__pycache__", "*.pyc")

RUNBOOK_SRC = REPO / "docs" / "agentcore-deploy-runbook.md"


def log(msg: str) -> None:
    print(f"  [export] {msg}", flush=True)


def _read_env() -> dict:
    """The public identifiers both bundles need, from this deployment's own outputs.

    None of these are secrets — they are the same values the browser apps ship. Read
    rather than hardcoded so an export against another account is correct by
    construction; a hand-copied pool id is exactly the silent 401 the runbook's A5.5
    exists to catch.
    """
    outputs = json.loads((REPO / "cdk-outputs.json").read_text())
    stack = next(iter(outputs.values()))
    state = json.loads((REPO / "agentcore-state.json").read_text())
    region = "us-west-2"
    return {
        "region": region,
        "registryId": state["registryId"],
        "userPoolId": stack["UserPoolId"],
        "userPoolClientId": stack["UserPoolClientId"],
        "cognitoTokenUrl": (
            f"https://smarthome-{_account_id()}.auth.{region}.amazoncognito.com"
            "/oauth2/token"),
        "scope": "a2a-server/invoke",
        "skillsTableName": "smarthome-skills",
        "adminConsoleUrl": stack["AdminConsoleUrl"],
        "chatbotUrl": stack["ChatbotUrl"],
    }


def _account_id() -> str:
    outputs = json.loads((REPO / "cdk-outputs.json").read_text())
    stack = next(iter(outputs.values()))
    # ChatbotBucketName is `smarthome-chatbot-<account>`; cheaper and more reliable
    # here than an STS call, which would make an offline export impossible.
    return stack["ChatbotBucketName"].rsplit("-", 1)[-1]


CONFIG_COMMENT = (
    "Everything the deploy and register scripts need. Regenerated by "
    "scripts/export-deploy-demo.py from cdk-outputs.json + agentcore-state.json. "
    "None of these are secrets — they are the same public identifiers the browser "
    "apps ship."
)


def _missing_demo_files() -> list[str]:
    missing = []
    for bundle, names in DEMO_ONLY.items():
        for name in names:
            if not (bundle / name).exists():
                missing.append(str((bundle / name).relative_to(OUT_DIR)))
    return missing


def _index_readme(env: dict, commit: str) -> str:
    return f"""# AgentCore 部署演示 — 索引

两条部署链路的可下载演示包 + 操作手册。由 `scripts/export-deploy-demo.py` 导出于
commit `{commit}`, 目标环境是当前这套部署 (us-west-2, registry `{env['registryId']}`)。

| 内容 | 说明 |
| --- | --- |
| [`agentcore-deploy-runbook.md`](agentcore-deploy-runbook.md) | **先看这个。** 两条链路串起来的操作流程、版本号语义、排错表、30 分钟演示时间表 |
| [`demo-agent-air-quality/`](demo-agent-air-quality/) | Flow A: A2A Sub-Agent。本地调试 → `agentcore deploy` → 注册 Registry → 审批 → 核对 authorizer → Admin Console → 给用户授权 |
| [`demo-skill-indoor-air-report/`](demo-skill-indoor-air-report/) | Flow B: Skill。写 `SKILL.md` → 发布 Registry → 审批 → Admin Console → 导入生效 |

每个包内有自己的 README(分步细节)、`demo-config.json`(已填好当前环境)和脚本。
两个包都是自包含的, 解压到任意目录即可运行, 不依赖仓库。

## 30 秒上手

```bash
# Flow A: 本地把子 Agent 跑起来
cd demo-agent-air-quality
pip install -r requirements.txt
AWS_REGION=us-west-2 python main.py          # 终端 1
AWS_REGION=us-west-2 python invoke_local.py  # 终端 2

# Flow B: 先确认基座是活的 (最省时间的前置检查)
cd ../demo-skill-indoor-air-report
pip install -r requirements.txt
python publish_skill.py --list               # 应列出已批准的内建 skill
```

## 四条要点

- **AgentCore CLI 没有 registry 子命令**(0.26/0.27)。Runtime 部署用 CLI, Registry
  注册用包内的 boto3 脚本。
- **注册让你被发现; 你自己 Runtime 的 authorizer 决定谁能调你。** 两个方向都会静默出错
  (谁都调不到 / 谁都能调), 所以 runbook 的 **A5.5** 是一步独立的核对。
- **升版会把已 APPROVED 的记录打回 DRAFT**, 而 Admin Console 和编排 agent 都只认
  APPROVED —— 升版是**有停机窗口**的变更。但授权不会丢: 有重新审批宽限期。
- **`DEPRECATED` 是终态, 且记录会从 API 上消失。** 想可逆地停用请用 `reject`。

导出内容的口径以仓库为准: `common/` 与 `agent_registry.py` 是从
`a2a-agent-registry/common/` 和 `shared/agent_registry.py` 直接复制的, 每次导出刷新。
"""


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="report what would change and write nothing")
    args = ap.parse_args(argv)

    if not OUT_DIR.exists():
        sys.exit(f"{OUT_DIR} does not exist. The demo-specific code lives only in the "
                 f"bundle; extract {TARBALL.name} first, then re-run.")
    missing = _missing_demo_files()
    if missing:
        sys.exit("refusing to write a broken bundle — these demo-only files are "
                 f"missing:\n  " + "\n  ".join(missing) +
                 f"\nRecover them from {TARBALL.name} first.")

    commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=REPO,
                            capture_output=True, text=True).stdout.strip() or "unknown"
    env = _read_env()

    if args.check:
        # Only the interesting drift: the copied runtime code.
        stale = []
        for src in sorted(COMMON_SRC.glob("*.py")):
            dst = AGENT_BUNDLE / "common" / src.name
            if not dst.exists():
                stale.append(f"MISSING  common/{src.name}")
            elif dst.read_bytes() != src.read_bytes():
                stale.append(f"STALE    common/{src.name}")
        for bundle in (AGENT_BUNDLE, SKILL_BUNDLE):
            dst = bundle / "agent_registry.py"
            canonical = (REPO / "shared" / "agent_registry.py").read_bytes()
            if not dst.exists() or dst.read_bytes() != canonical:
                stale.append(f"STALE    {bundle.name}/agent_registry.py")
        actor_dst = AGENT_BUNDLE / "memory_actor.py"
        actor_src = (REPO / "shared" / "memory_actor.py").read_bytes()
        if not actor_dst.exists():
            stale.append("MISSING  demo-agent-air-quality/memory_actor.py")
        elif actor_dst.read_bytes() != actor_src:
            stale.append("STALE    demo-agent-air-quality/memory_actor.py")
        print("\n".join(stale) if stale else "bundle is current")
        return 1 if stale else 0

    # 1. common/ — wholesale, so a new module cannot be forgotten.
    dst_common = AGENT_BUNDLE / "common"
    if dst_common.exists():
        shutil.rmtree(dst_common)
    shutil.copytree(COMMON_SRC, dst_common, ignore=COMMON_IGNORE)
    names = sorted(p.name for p in dst_common.glob("*.py"))
    log(f"common/: {len(names)} module(s) -> {', '.join(names)}")

    # 2. The Registry helper, into both bundles.
    for bundle in (AGENT_BUNDLE, SKILL_BUNDLE):
        shutil.copy2(REPO / "shared" / "agent_registry.py",
                     bundle / "agent_registry.py")
    log("agent_registry.py refreshed in both bundles")

    # 3. The Memory actor rule. `common/memory.py` reaches for it by path — in a real
    #    deployment `deploy.py` copies all of `shared/` next to the agent code, but a
    #    bundle that claims to be self-contained has to carry it. Without it the demo
    #    agent silently loses memory: `memory_actor_for` swallows the ImportError and
    #    returns "", so every namespace resolves to nothing and it looks like the user
    #    simply has no history. Found by extracting the tarball and importing it.
    shutil.copy2(REPO / "shared" / "memory_actor.py",
                 AGENT_BUNDLE / "memory_actor.py")
    log("memory_actor.py copied next to common/ (self-contained memory)")

    # 4. Config, from the live outputs.
    for bundle in (AGENT_BUNDLE, SKILL_BUNDLE):
        keys = (env if bundle is AGENT_BUNDLE
                else {k: env[k] for k in ("region", "registryId", "skillsTableName",
                                          "adminConsoleUrl")})
        (bundle / "demo-config.json").write_text(
            json.dumps({"_comment": CONFIG_COMMENT, **keys},
                       indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    log(f"demo-config.json regenerated (registry {env['registryId']})")

    # 5. Docs.
    shutil.copy2(RUNBOOK_SRC, OUT_DIR / "agentcore-deploy-runbook.md")
    (OUT_DIR / "README.md").write_text(_index_readme(env, commit), encoding="utf-8")
    log("runbook + index README written")

    # 6. Tarball. Rebuilt from scratch so a file removed upstream does not survive
    #    inside it, which is how a tarball and a directory drift apart.
    if TARBALL.exists():
        TARBALL.unlink()
    with tarfile.open(TARBALL, "w:gz") as tar:
        tar.add(OUT_DIR, arcname=OUT_DIR.name,
                filter=lambda ti: None if "__pycache__" in ti.name else ti)
    files = sum(1 for _ in OUT_DIR.rglob("*") if _.is_file())
    log(f"{TARBALL.relative_to(REPO)} -> {TARBALL.stat().st_size // 1024} KB, "
        f"{files} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
